name: Release
permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win
          - os: ubuntu-latest
            platform: linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: 1.4.3

      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate icons
        run: bun scripts/generate-icon.mjs

      - name: Build
        run: bun run build:release

      - name: Upload Windows artifact
        if: matrix.platform == 'win'
        uses: softprops/action-gh-release@v2.2.0
        with:
          files: |
            release/**/involvex-term-Windows-*-Setup.exe
            release/**/involvex-term-Windows-*-Setup.exe.blockmap
            release/**/latest.yml
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux artifact
        if: matrix.platform == 'linux'
        uses: softprops/action-gh-release@v2.2.0
        with:
          files: |
            release/**/involvex-term-Linux-*.AppImage
            release/**/latest-linux.yml
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
